### ISSUE TITLE
Update Angular version

### ISSUE THREAD

**Issue by sujeethk** [teamfa/angular-toasty#40]
It is causing dependency conflict with other libraries. Can this be updated to angular 1.5.8?

**Comment by warrendodsworth** [comment]
+1

**Comment by azachar** [comment]
+1

**Comment by MaksSlesarenko** [comment]
+1

**Comment by Ehesp** [comment]
https://github.com/teamfa/angular-toasty/commit/cd040c99002b8650e95872c72ce661f527b2f264

**Comment by azachar** [comment]
+1
